options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/hr-management-2025/calculator-repo/calculator:latest', '.']

  # Step 2: Push to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/hr-management-2025/calculator-repo/calculator:latest']

  # Step 3: Terraform init
  - name: 'hashicorp/terraform'
    entrypoint: 'terraform'
    args: ['init']

  # Step 4: Terraform plan
  - name: 'hashicorp/terraform'
    entrypoint: 'terraform'
    args: ['plan']

  # Step 5: Terraform apply
  - name: 'hashicorp/terraform'
    entrypoint: 'terraform'
    args: ['apply', '-auto-approve']